server:
  port: 9004

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  data:
    mongodb:
      #host: localhost
      #port: 27017
      database: mitocodedb
      uri: mongodb://mitocode:mitocode@localhost:27017
      #username: mitocode
      #password: mitocode
      authentication-database: admin

encrypt:
  key: FernandoBetancourt

info:
  app:
    name: User Service Microservice
    description: Módulo de la arquitectura que disponibiliza información de los usuarios
    version: 1.0

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  info:
    env:
      enabled: true
